AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  eventbridge-integration-solution-zendesk-ticket-translations

  (qs-1qp3lnajg)

Metadata:
  AWS::ServerlessRepo::Application:
    Name: Amazon-EventBridge-Integration-Solution-Zendesk-Ticket-Translations
    Description: This application demonstrates an integration with AWS Step Functions, AWS Lambda, and Amazon Translate for Amazon EventBridge SaaS Partner Zendesk
    Author: AWS Quick Start
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
    - amazon
    - eventbridge
    - integration
    - solution
    - aws
    - lambda
    - step_functions
    - zendesk
    - translate
    HomePageUrl: https://github.com/aws-quickstart/eventbridge-integration-solution-zendesk-ticket-translations
    SemanticVersion: 0.1.2
    SourceCodeUrl: https://github.com/aws-quickstart/eventbridge-integration-solution-zendesk-ticket-translations
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Amazon EventBridge Integration Solution
      Parameters:
      - EventSourceName
      - TargetLanguage
    - Label:
        default: Zendesk Configuration
      Parameters:
      - ZendeskSubdomain
      - ZendeskEmail
      - ZendeskAPIToken
    ParameterLabels:
      EventSourceName:
        default: Event Source Name
      TargetLanguage:
        default: Target Language
      ZendeskAPIToken:
        default: API Token
      ZendeskEmail:
        default: Email
      ZendeskSubdomain:
        default: Subdomain

Parameters:
  EventSourceName:
    Type: String
    AllowedPattern: aws\.partner(/[\.\-_A-Za-z0-9]+){2,}
    MinLength: 1
    MaxLength: 256
    Description: Name of the Amazon EventBridge Zendesk Event Source to associate with an Event Bus. For example, aws.partner/zendesk.com/123456/default
  TargetLanguage:
    Type: String
    Default: en
    MinLength: 2
    MaxLength: 5
    Description: The language you want to translate to. For more details, visit https://docs.aws.amazon.com/translate/latest/dg/what-is.html#what-is-languages
  ZendeskAPIToken:
    Type: String
    NoEcho: true
    MinLength: 1
    Description: The Zendesk API token used to access the Zendesk API
  ZendeskEmail:
    Type: String
    MinLength: 1
    Description: The Zendesk agent email used for Zendesk API access
  ZendeskSubdomain:
    Type: String
    MinLength: 1
    Description: The Zendesk subdomain which is a unique identifier of your Zendesk account

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        email: !Ref ZendeskEmail
        subdomain: !Ref ZendeskSubdomain
        token: !Ref ZendeskAPIToken
        target_language: !Ref TargetLanguage
Resources:
#############
#  Lambdas  #
#############
  GetTicket:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get_ticket
      Handler: app.lambda_handler
      Runtime: python3.8
  TranslateTicket:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/translate_ticket
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - ComprehendBasicAccessPolicy: {}
        - Statement:
          - Sid: TranslateTextPolicy
            Effect: Allow
            Action: translate:TranslateText
            Resource: "*"
  PostComment:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/post_comment
      Handler: app.lambda_handler
      Runtime: python3.8
#################
#  EventBridge  #
#################
  EventBridgeEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Ref EventSourceName
      EventSourceName: !Ref EventSourceName
  ZendeskTranslateRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: Takes comments on tickets and runs them through Step Functions
      EventBusName: !Ref EventBridgeEventBus
      EventPattern:
        account:
        - !Ref "AWS::AccountId"
        detail-type:
        - 'Support Ticket: Comment Created'
      State: ENABLED
      Targets: 
      - Arn:  !Ref TheTranslator
        Id: TheTranslator
        RoleArn: !GetAtt EventBridgeInvokeTranslator.Arn
  EventBridgeInvokeTranslator:
    Type: AWS::IAM::Role
    Properties: 
      Description: Role for invoking StepFunctions
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - events.amazonaws.com
          Action: "sts:AssumeRole"
      Policies:
      - PolicyName: EventBridgeInvokeTranslatorPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - states:StartExecution
            Resource:
            - !Ref TheTranslator

###################
#  StepFunctions  #
###################
  TheTranslator:
    Type: AWS::StepFunctions::StateMachine
    Properties: 
      DefinitionString: !Sub |
        {
          "Comment": "Translating Zendesk Tickets with EventBridge, Step Functions, Lambda, and Translate.",
          "StartAt": "GetTicket",
          "States": {
            "GetTicket": {
              "Type": "Task",
              "Resource": "arn:aws:states:::lambda:invoke",
              "Parameters": {
                "FunctionName": "${GetTicket}",
                "Payload": {
                  "detail-type.$": "$.detail-type",
                  "id.$": "$.detail.ticket_event.ticket.id",
                  "content.$": "$.detail.ticket_event"
                }
              },
              "Next": "TranslateTicket"
            },
            "TranslateTicket": {
              "Type": "Task",
              "Resource": "arn:aws:states:::lambda:invoke",
              "Parameters": {
                "FunctionName": "${TranslateTicket}",
                "Payload": {
                  "Input.$": "$.Payload"
                }
              },
              "Next": "toTranslateOrNot"
              },
              "toTranslateOrNot": {
                "Type": "Choice",
                "Choices": [
                  {
                    "Not": {
                      "Variable": "$.Payload.Original_Langugage",
                      "StringEquals": "$.Payload.To_Language"
                    },
                    "Next": "PostComment"
                  },
                  {
                    "Variable": "$.Payload.Original_Langugage",
                    "StringEquals": "$.Payload.To_Languages",
                    "Next": "EndState"
                  }
                ],
                "Default": "PostComment"
              },
              "PostComment": {
                "Type": "Task",
                "Resource": "arn:aws:states:::lambda:invoke",
                "Parameters": {
                  "FunctionName": "${PostComment}",
                  "Payload": {
                    "Input.$": "$.Payload"
                  }
                },
                "End": true
              },
              "EndState": {
                "Type": "Succeed"
              }
            }
          }
      RoleArn: !GetAtt TheTranslatorRole.Arn
      StateMachineName: TheTranslator
      StateMachineType: EXPRESS
  TheTranslatorRole:
    Type: AWS::IAM::Role
    Properties: 
      Description: Role for invoking Lambdas
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - !Sub states.${AWS::Region}.amazonaws.com
          Action: "sts:AssumeRole"
      Path: "/"
      Policies:
      - PolicyName: TheTranslatorPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "lambda:InvokeFunction"
            Resource:
            - !GetAtt GetTicket.Arn
            - !GetAtt TranslateTicket.Arn
            - !GetAtt PostComment.Arn
          - Effect: Allow
            Action:
            - logs:CreateLogDelivery
            - logs:GetLogDelivery
            - logs:UpdateLogDelivery
            - logs:DeleteLogDelivery
            - logs:ListLogDeliveries
            - logs:PutResourcePolicy
            - logs:DescribeResourcePolicies
            - logs:DescribeLogGroups
            Resource: "*"
Outputs:
  EventBridgeEventBus:
    Description: SaaS Event Bus ARN
    Value: !GetAtt EventBridgeEventBus.Arn
  EventBridgeRule:
    Description: EventBridge Rule ARN
    Value: !GetAtt ZendeskTranslateRule.Arn
  GetTicketFunction:
    Description: GetTicket Function ARN
    Value: !GetAtt GetTicket.Arn
  TranslateTicketFunction:
    Description: TranslateTicket Function ARN
    Value: !GetAtt TranslateTicket.Arn
  PostCommentFunction:
    Description: PostComment Function ARN
    Value: !GetAtt PostComment.Arn
